### ISSUE TITLE
Idea: Navigation bar

### ISSUE THREAD

**Issue by goofballLogic** [IainCarlisle118/NewsSite#1]
When you click the "Hot" or "United States" navigation links, the search results seem to change but the "active" highlight doesn't change to reflect the new location.

Would you be interested in a pull request fixing this?

**Comment by IainCarlisle118** [comment]
@goofballLogic that sounds great!  I have added you as a collaborator on the repo.

**Comment by IainCarlisle118** [comment]
Closed out by 2f609c2
