### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by goofballLogic** [IainCarlisle118/NewsSite#3]
![image](https://user-images.githubusercontent.com/910448/37618882-8376d23c-2baf-11e8-9ee9-b4a70e05f8e2.png)

Screenshot shows incorrect encoding of extended quote characters (around _enormously exciting_) . Here's how they look in the JSON:

![image](https://user-images.githubusercontent.com/910448/37618921-a909f8d0-2baf-11e8-8d0c-9f7fcc74f2a8.png)

**Comment by IainCarlisle118** [comment]
87bd61b closes this out.  Committed to dev

**Comment by goofballLogic** [comment]
Hi Iain, is this published?

**Comment by IainCarlisle118** [comment]
Apologies!  Seemed to only be up on development branch, it is pubished now
