### ISSUE TITLE
Multiple <head> elements rendered

### ISSUE THREAD

**Issue by goofballLogic** [IainCarlisle118/NewsSite#4]
The HTML of the site is emitted with multiple <head> elements. The second one is cleaned up by the browser because it occurs inside the <body> element, but still....

![image](https://user-images.githubusercontent.com/910448/37765232-94397382-2dbb-11e8-84be-787abfff7d58.png)

**Comment by IainCarlisle118** [comment]
f3f83f2 closes this out
